# Generated by Django 4.2 on 2023-05-24 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='correctness_degree',
            field=models.SmallIntegerField(default=0),
        ),
    ]
