# Generated by Django 4.2 on 2023-06-15 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('askme', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={},
        ),
    ]
